### ISSUE TITLE
Add new color scheme (black background with green text)

### ISSUE THREAD

**Issue by dgwillim** [blanboom/AirTerminal#2]
Any chance you could add a black background with green text?

or the ability to add custom Color Themes?

**Comment by blanboom** [comment]
Thank you for your suggestion. I will include a new color scheme, *HaX0R_GR33N*, in AirTerminal 2.2.1. Please test it using the following TestFlight link:

- https://testflight.apple.com/join/kF4k23Zr

Additionally, you might want to explore https://iterm2colorschemes.com for more themes. Do let me know if there are any specific ones you would like added to AirTerminal.

Custom color schemes will be added in the next major release.

**Comment by dgwillim** [comment]
Perfect! Sent you feedback via TestFlight.

If you can add:

HaX0R_BLUE
HaX0R_R3D
Retro

**Comment by blanboom** [comment]
Added HaX0R_BLUE, HaX0R_R3D, and Retro themes in the latest TestFlight version.

**Comment by dgwillim** [comment]
Awesome! Thank you so much!

**Comment by blanboom** [comment]
AirTerminal 2.2.1 is released in App Store.

**Comment by blanboom** [comment]
New color schemes are added in AirTerminal 2.2.1 and released in App Store.
